"Component: Frontend":
  - frontend/**/*
"Component: Backend":
  - backend/**/*
  - tests/**/*
  - migrations/**/*
  - ./manage.py
  - ./requirements.txt
"Component: Infrastructure":
  - .circleci/*
  - .github/**/*
  - scripts/aws/**/*
  - scripts/docker/**/*
  - scripts/install/**/*
  - docker-*.yml
